window.RasigaSeeds = [
  { id: 's01', title: 'Lag Ja Gale', film: 'Woh Kaun Thi', language: 'Hindi', industry: 'Bollywood', year: 1964, composer: 'Madan Mohan', singer: 'Lata Mangeshkar', lyricist: 'Raja Mehdi Ali Khan', raga: null, genre: ['Romantic', 'Classic'], mood: ['Nostalgic', 'Soulful'], avg_rating: 4.9, total_ratings: 62450 },
  { id: 's02', title: 'Chaiyya Chaiyya', film: 'Dil Se', language: 'Hindi', industry: 'Bollywood', year: 1998, composer: 'A.R. Rahman', singer: 'Sukhwinder Singh', lyricist: 'Gulzar', raga: null, genre: ['Sufi', 'Fusion'], mood: ['Energetic', 'Spiritual'], avg_rating: 4.8, total_ratings: 78320 },
  { id: 's03', title: 'Enna Solla Pogirai', film: 'Kandukondain Kandukondain', language: 'Tamil', industry: 'Kollywood', year: 2000, composer: 'A.R. Rahman', singer: 'Unnikrishnan', lyricist: 'Vairamuthu', raga: 'Kalyani', genre: ['Romantic', 'Classical Fusion'], mood: ['Melancholic', 'Soulful'], avg_rating: 4.9, total_ratings: 42100 },
  { id: 's04', title: 'Kaadhal Rojave', film: 'Roja', language: 'Tamil', industry: 'Kollywood', year: 1992, composer: 'A.R. Rahman', singer: 'Minmini', lyricist: 'Vairamuthu', raga: 'Kharaharapriya', genre: ['Romantic', 'Folk Fusion'], mood: ['Longing', 'Nostalgic'], avg_rating: 4.8, total_ratings: 51200 },
  { id: 's05', title: 'Tum Hi Ho', film: 'Aashiqui 2', language: 'Hindi', industry: 'Bollywood', year: 2013, composer: 'Mithoon', singer: 'Arijit Singh', lyricist: 'Mithoon', raga: null, genre: ['Romantic', 'Sad'], mood: ['Melancholic', 'Heartbroken'], avg_rating: 4.6, total_ratings: 45231 },
  { id: 's06', title: 'Malare', film: 'Premam', language: 'Malayalam', industry: 'Mollywood', year: 2015, composer: 'Rajesh Murugesan', singer: 'Vijay Yesudas', lyricist: 'Shaan Rahman', raga: null, genre: ['Romantic', 'Indie'], mood: ['Nostalgic', 'Bittersweet'], avg_rating: 4.8, total_ratings: 34560 },
  { id: 's07', title: 'Munbe Vaa', film: 'Sillunu Oru Kaadhal', language: 'Tamil', industry: 'Kollywood', year: 2006, composer: 'A.R. Rahman', singer: 'Hariharan, Shreya Ghoshal', lyricist: 'Vairamuthu', raga: null, genre: ['Romantic', 'Classical'], mood: ['Soulful', 'Peaceful'], avg_rating: 4.8, total_ratings: 44560 },
  { id: 's08', title: 'Kal Ho Naa Ho', film: 'Kal Ho Na Ho', language: 'Hindi', industry: 'Bollywood', year: 2003, composer: 'Shankar-Ehsaan-Loy', singer: 'Sonu Nigam', lyricist: 'Javed Akhtar', raga: null, genre: ['Emotional', 'Romantic'], mood: ['Bittersweet', 'Motivational'], avg_rating: 4.7, total_ratings: 55890 },
  { id: 's09', title: 'Nenjukkul Peidhidum', film: 'Vaaranam Aayiram', language: 'Tamil', industry: 'Kollywood', year: 2008, composer: 'Harris Jayaraj', singer: 'Karthik', lyricist: 'Na. Muthukumar', raga: null, genre: ['Romantic', 'Soft Rock'], mood: ['Joyful', 'Energetic'], avg_rating: 4.7, total_ratings: 39870 },
  { id: 's10', title: 'Ekla Cholo Re', film: 'Kahaani', language: 'Bengali', industry: 'Bengali Cinema', year: 2012, composer: 'Usha Uthup', singer: 'Amitabh Bachchan', lyricist: 'Rabindranath Tagore', raga: null, genre: ['Folk', 'Patriotic'], mood: ['Motivational', 'Spiritual'], avg_rating: 4.9, total_ratings: 29870 },
  { id: 's11', title: 'Bombe Heluthaite', film: 'Mungaru Male', language: 'Kannada', industry: 'Sandalwood', year: 2006, composer: 'V. Harikrishna', singer: 'Rajesh Krishnan', lyricist: 'R.N. Jayagopal', raga: null, genre: ['Romantic', 'Pop'], mood: ['Joyful', 'Romantic'], avg_rating: 4.6, total_ratings: 21450 },
  { id: 's12', title: 'Nuvvu Nenu', film: 'Okkadu', language: 'Telugu', industry: 'Tollywood', year: 2003, composer: 'Mani Sharma', singer: 'Udit Narayan, Madhushree', lyricist: 'Sirivennela Seetharama Sastry', raga: null, genre: ['Romantic', 'Classical'], mood: ['Joyful', 'Romantic'], avg_rating: 4.6, total_ratings: 28900 },
  { id: 's13', title: 'Tere Bina', film: 'Guru', language: 'Hindi', industry: 'Bollywood', year: 2007, composer: 'A.R. Rahman', singer: 'A.R. Rahman, Chinmayi', lyricist: 'Gulzar', raga: null, genre: ['Romantic', 'Fusion'], mood: ['Longing', 'Soulful'], avg_rating: 4.5, total_ratings: 38760 },
  { id: 's14', title: 'Thumbi Vaa', film: 'Ennu Ninte Moideen', language: 'Malayalam', industry: 'Mollywood', year: 2015, composer: 'M. Jayachandran', singer: 'P. Unnikrishnan', lyricist: 'P. Bhaskaran', raga: null, genre: ['Romantic', 'Classical'], mood: ['Soulful', 'Nostalgic'], avg_rating: 4.7, total_ratings: 18760 },
  { id: 's15', title: 'Phir Le Aya Dil', film: 'Barfi!', language: 'Hindi', industry: 'Bollywood', year: 2012, composer: 'Pritam', singer: 'Rekha Bhardwaj', lyricist: 'Swanand Kirkire', raga: null, genre: ['Romantic', 'Folk'], mood: ['Nostalgic', 'Soulful'], avg_rating: 4.7, total_ratings: 28760 },
  { id: 's16', title: 'Vinnaithaandi Varuvaayaa', film: 'Vinnaithaandi Varuvaayaa', language: 'Tamil', industry: 'Kollywood', year: 2010, composer: 'A.R. Rahman', singer: 'Benny Dayal, Shreya Ghoshal', lyricist: 'Thamarai', raga: null, genre: ['Romantic', 'Pop'], mood: ['Joyful', 'Dreamy'], avg_rating: 4.7, total_ratings: 36450 },
  { id: 's17', title: 'Ye Maya Chesave', film: 'Ye Maya Chesave', language: 'Telugu', industry: 'Tollywood', year: 2010, composer: 'A.R. Rahman', singer: 'Benny Dayal', lyricist: 'Chandrabose', raga: null, genre: ['Romantic', 'Fusion'], mood: ['Dreamy', 'Romantic'], avg_rating: 4.5, total_ratings: 25670 },
  { id: 's18', title: 'Kannaana Kanney', film: 'Viswasam', language: 'Tamil', industry: 'Kollywood', year: 2019, composer: 'D. Imman', singer: 'Sid Sriram', lyricist: 'Yugabharathi', raga: null, genre: ['Devotional', 'Emotional'], mood: ['Spiritual', 'Soulful'], avg_rating: 4.6, total_ratings: 19450 },
  { id: 's19', title: 'Kesariya', film: 'Brahmastra', language: 'Hindi', industry: 'Bollywood', year: 2022, composer: 'Pritam', singer: 'Arijit Singh', lyricist: 'Amitabh Bhattacharya', raga: null, genre: ['Romantic', 'Pop'], mood: ['Dreamy', 'Romantic'], avg_rating: 4.4, total_ratings: 67800 },
  { id: 's20', title: 'Zinda', film: 'Bhaag Milkha Bhaag', language: 'Hindi', industry: 'Bollywood', year: 2013, composer: 'Shankar-Ehsaan-Loy', singer: 'Siddharth Mahadevan', lyricist: 'Prasoon Joshi', raga: null, genre: ['Motivational', 'Rock'], mood: ['Motivational', 'Energetic'], avg_rating: 4.6, total_ratings: 31200 },
  { id: 's21', title: 'Rowdy Baby', film: 'Maari 2', language: 'Tamil', industry: 'Kollywood', year: 2018, composer: 'Yuvan Shankar Raja', singer: 'Dhanush, Dhee', lyricist: 'Yugabharathi', raga: null, genre: ['Dance', 'Pop'], mood: ['Energetic', 'Joyful'], avg_rating: 4.5, total_ratings: 89500 },
  { id: 's22', title: 'Channa Mereya', film: 'Ae Dil Hai Mushkil', language: 'Hindi', industry: 'Bollywood', year: 2016, composer: 'Pritam', singer: 'Arijit Singh', lyricist: 'Amitabh Bhattacharya', raga: null, genre: ['Romantic', 'Sad'], mood: ['Heartbroken', 'Soulful'], avg_rating: 4.7, total_ratings: 71200 }
];

window.RasigaReviews = [
  { name: 'Rahul V.', clr: '#f97316', text: 'This song takes me back to my childhood. Lata ji\'s voice floats over the orchestra like moonlight. Absolutely timeless.', quote: '"Lag jaa gale ke phir ye haseen raat ho na ho..."', rating: 5, song: 'Lag Ja Gale', likes: 124, time: '2 days ago' },
  { name: 'Priya K.', clr: '#ec4899', text: 'Rahman at his absolute peak. The train-top energy, the Sufi lyrics, Sukhwinder\'s raw power — nothing comes close.', quote: '"Jinke sar ho ishq ki chaaon..."', rating: 5, song: 'Chaiyya Chaiyya', likes: 89, time: '3 days ago' },
  { name: 'Arjun S.', clr: '#0d9488', text: 'Good composition and Arijit delivers, but honestly it\'s overrated compared to classic heartbreak songs.', quote: null, rating: 3.5, song: 'Tum Hi Ho', likes: 12, time: '1 week ago' },
  { name: 'Meera T.', clr: '#8b5cf6', text: 'A masterpiece. Hariharan and Shreya\'s chemistry is magical. I listen to this every morning.', quote: '"Munbe vaa en anbae vaa..."', rating: 5, song: 'Munbe Vaa', likes: 256, time: '4 days ago' }
];

window.RasigaSuggestions = [
  { id: 'sug01', song: 'Munbe Vaa', year: 2006, director: 'A.R. Rahman', singer: 'Shreya Ghoshal, Naresh Iyer', lyricist: 'Vaali', status: 'Approved', timestamp: Date.now() - 86400000 },
  { id: 'sug02', song: 'Pudhu Vellai Mazhai', year: 1992, director: 'A.R. Rahman', singer: 'Unni Menon, Sujatha', lyricist: 'Vairamuthu', status: 'Pending', timestamp: Date.now() - 3600000 },
  { id: 'sug03', song: 'Rowdy Baby', year: 2018, director: 'Yuvan Shankar Raja', singer: 'Dhanush, Dhee', lyricist: 'Poetu Dhanush', status: 'Duplicate', timestamp: Date.now() - 172800000 }
];
