INSERT INTO songs (
  title, 
  film, 
  language, 
  industry, 
  year, 
  composer, 
  singer, 
  lyricist, 
  raga, 
  genre, 
  mood, 
  avg_rating, 
  total_ratings
) VALUES
('Lag Ja Gale', 'Woh Kaun Thi', 'Hindi', 'Bollywood', 1964, 'Madan Mohan', 'Lata Mangeshkar', 'Raja Mehdi Ali Khan', NULL, ARRAY['Romantic','Classic'], ARRAY['Nostalgic','Soulful'], 4.9, 62450),
('Chaiyya Chaiyya', 'Dil Se', 'Hindi', 'Bollywood', 1998, 'A.R. Rahman', 'Sukhwinder Singh', 'Gulzar', NULL, ARRAY['Sufi','Fusion'], ARRAY['Energetic','Spiritual'], 4.8, 78320),
('Enna Solla Pogirai', 'Kandukondain Kandukondain', 'Tamil', 'Kollywood', 2000, 'A.R. Rahman', 'Unnikrishnan', 'Vairamuthu', 'Kalyani', ARRAY['Romantic','Classical Fusion'], ARRAY['Melancholic','Soulful'], 4.9, 42100),
('Kaadhal Rojave', 'Roja', 'Tamil', 'Kollywood', 1992, 'A.R. Rahman', 'Minmini', 'Vairamuthu', 'Kharaharapriya', ARRAY['Romantic','Folk Fusion'], ARRAY['Longing','Nostalgic'], 4.8, 51200),
('Tum Hi Ho', 'Aashiqui 2', 'Hindi', 'Bollywood', 2013, 'Mithoon', 'Arijit Singh', 'Mithoon', NULL, ARRAY['Romantic','Sad'], ARRAY['Melancholic','Heartbroken'], 4.6, 45231),
('Malare', 'Premam', 'Malayalam', 'Mollywood', 2015, 'Rajesh Murugesan', 'Vijay Yesudas', 'Shaan Rahman', NULL, ARRAY['Romantic','Indie'], ARRAY['Nostalgic','Bittersweet'], 4.8, 34560),
('Munbe Vaa', 'Sillunu Oru Kaadhal', 'Tamil', 'Kollywood', 2006, 'A.R. Rahman', 'Hariharan, Shreya Ghoshal', 'Vairamuthu', NULL, ARRAY['Romantic','Classical'], ARRAY['Soulful','Peaceful'], 4.8, 44560),
('Kal Ho Naa Ho', 'Kal Ho Na Ho', 'Hindi', 'Bollywood', 2003, 'Shankar-Ehsaan-Loy', 'Sonu Nigam', 'Javed Akhtar', NULL, ARRAY['Emotional','Romantic'], ARRAY['Bittersweet','Motivational'], 4.7, 55890),
('Nenjukkul Peidhidum', 'Vaaranam Aayiram', 'Tamil', 'Kollywood', 2008, 'Harris Jayaraj', 'Karthik', 'Na. Muthukumar', NULL, ARRAY['Romantic','Soft Rock'], ARRAY['Joyful','Energetic'], 4.7, 39870),
('Ekla Cholo Re', 'Kahaani', 'Bengali', 'Bengali Cinema', 2012, 'Usha Uthup', 'Amitabh Bachchan', 'Rabindranath Tagore', NULL, ARRAY['Folk','Patriotic'], ARRAY['Motivational','Spiritual'], 4.9, 29870),
('Bombe Heluthaite', 'Mungaru Male', 'Kannada', 'Sandalwood', 2006, 'V. Harikrishna', 'Rajesh Krishnan', 'R.N. Jayagopal', NULL, ARRAY['Romantic','Pop'], ARRAY['Joyful','Romantic'], 4.6, 21450),
('Nuvvu Nenu', 'Okkadu', 'Telugu', 'Tollywood', 2003, 'Mani Sharma', 'Udit Narayan, Madhushree', 'Sirivennela Seetharama Sastry', NULL, ARRAY['Romantic','Classical'], ARRAY['Joyful','Romantic'], 4.6, 28900),
('Tere Bina', 'Guru', 'Hindi', 'Bollywood', 2007, 'A.R. Rahman', 'A.R. Rahman, Chinmayi', 'Gulzar', NULL, ARRAY['Romantic','Fusion'], ARRAY['Longing','Soulful'], 4.5, 38760),
('Thumbi Vaa', 'Ennu Ninte Moideen', 'Malayalam', 'Mollywood', 2015, 'M. Jayachandran', 'P. Unnikrishnan', 'P. Bhaskaran', NULL, ARRAY['Romantic','Classical'], ARRAY['Soulful','Nostalgic'], 4.7, 18760),
('Phir Le Aya Dil', 'Barfi!', 'Hindi', 'Bollywood', 2012, 'Pritam', 'Rekha Bhardwaj', 'Swanand Kirkire', NULL, ARRAY['Romantic','Folk'], ARRAY['Nostalgic','Soulful'], 4.7, 28760),
('Vinnaithaandi Varuvaayaa', 'Vinnaithaandi Varuvaayaa', 'Tamil', 'Kollywood', 2010, 'A.R. Rahman', 'Benny Dayal, Shreya Ghoshal', 'Thamarai', NULL, ARRAY['Romantic','Pop'], ARRAY['Joyful','Dreamy'], 4.7, 36450),
('Ye Maya Chesave', 'Ye Maya Chesave', 'Telugu', 'Tollywood', 2010, 'A.R. Rahman', 'Benny Dayal', 'Chandrabose', NULL, ARRAY['Romantic','Fusion'], ARRAY['Dreamy','Romantic'], 4.5, 25670),
('Kannaana Kanney', 'Viswasam', 'Tamil', 'Kollywood', 2019, 'D. Imman', 'Sid Sriram', 'Yugabharathi', NULL, ARRAY['Devotional','Emotional'], ARRAY['Spiritual','Soulful'], 4.6, 19450),
('Kesariya', 'Brahmastra', 'Hindi', 'Bollywood', 2022, 'Pritam', 'Arijit Singh', 'Amitabh Bhattacharya', NULL, ARRAY['Romantic','Pop'], ARRAY['Dreamy','Romantic'], 4.4, 67800),
('Zinda', 'Bhaag Milkha Bhaag', 'Hindi', 'Bollywood', 2013, 'Shankar-Ehsaan-Loy', 'Siddharth Mahadevan', 'Prasoon Joshi', NULL, ARRAY['Motivational','Rock'], ARRAY['Motivational','Energetic'], 4.6, 31200),
('Rowdy Baby', 'Maari 2', 'Tamil', 'Kollywood', 2018, 'Yuvan Shankar Raja', 'Dhanush, Dhee', 'Yugabharathi', NULL, ARRAY['Dance','Pop'], ARRAY['Energetic','Joyful'], 4.5, 89500),
('Channa Mereya', 'Ae Dil Hai Mushkil', 'Hindi', 'Bollywood', 2016, 'Pritam', 'Arijit Singh', 'Amitabh Bhattacharya', NULL, ARRAY['Romantic','Sad'], ARRAY['Heartbroken','Soulful'], 4.7, 71200);
